apiVersion: v1
kind: Service
metadata:
  name: {{ include "asset-management.fullname" . }}
  labels:
    {{- include "asset-management.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "asset-management.selectorLabels" . | nindent 4 }}
